// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBHhQF6wIt8yEvLjDFGKykYl9aIo1InEpE',
    appId: '1:438775683533:web:721d3631f8bb35617f4c84',
    messagingSenderId: '438775683533',
    projectId: 'flutter-push-8cf51',
    authDomain: 'flutter-push-8cf51.firebaseapp.com',
    storageBucket: 'flutter-push-8cf51.appspot.com',
    measurementId: 'G-V9FYM0WQ1K',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCFhSrnC5sYKK5f5TPubW9BWqfpL03eYiw',
    appId: '1:438775683533:android:3dfd9e1396404ebb7f4c84',
    messagingSenderId: '438775683533',
    projectId: 'flutter-push-8cf51',
    storageBucket: 'flutter-push-8cf51.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAIYrBkJS3E98f9ZtT56CP_tb9wV6Ow6ik',
    appId: '1:438775683533:ios:272d7b3371f68a847f4c84',
    messagingSenderId: '438775683533',
    projectId: 'flutter-push-8cf51',
    storageBucket: 'flutter-push-8cf51.appspot.com',
    iosBundleId: 'com.example.frontendapp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAIYrBkJS3E98f9ZtT56CP_tb9wV6Ow6ik',
    appId: '1:438775683533:ios:3bb231725b7960b77f4c84',
    messagingSenderId: '438775683533',
    projectId: 'flutter-push-8cf51',
    storageBucket: 'flutter-push-8cf51.appspot.com',
    iosBundleId: 'com.example.frontendapp.RunnerTests',
  );
}
